(function(w){if(w["oBALazyLoadId"]==undefined)w["oBALazyLoadId"]=[];if(w["BA_CORE_10"])return;w["BA_CORE_10"]=true;var FD=new function(){var s=this;s.i=false;var sf="ShockwaveFlash";var v="version";var aDR=[{"name":sf+"."+sf+".7",v:function(o){return gAV(o);}},{"name":sf+"."+sf+".6",v:function(o){var v="6,0,21";try{o.AllowScriptAccess="always";v=gAV(o);}catch(err){}
return v;}},{"name":sf+"."+sf,v:function(o){return gAV(o);}}];var gAV=function(axo){var v=-1;try{v=axo.GetVariable("$"+v);}catch(err){}
return v;};var gAO=function(n){var o=-1;try{o=new ActiveXObject(n);}catch(err){o={e:true};}
return o;};s.FD=function(){var n=navigator;if(n.plugins&&n.plugins.length>0){var t='application/x-shockwave-flash';var mT=n.mimeTypes;if(mT&&mT[t]&&mT[t].enabledPlugin&&mT[t].enabledPlugin.description){s.i=true;}}
else if(n.appVersion.indexOf("Mac")==-1&&window.execScript){var v=-1;for(var i=0;i<aDR.length&&v==-1;i++){var o=gAO(aDR[i].name);if(!o.e){s.i=true;}}}}();};function BA_CORE(){this.sBID="20081124000079";this.sFID="1";this.sMID="20070331000003"}BA_CORE.prototype={oD:document,sAD:"BA_AD"+(""=="w"?"1":"0"=="1"?"0":"_1"),
sTL:top!=self?document.referrer:location.href,sLH:location.host,rAMID:/ba_amid=(\d+)/i,rMSID:/ba_msid=(\d+)/i,rDemoType:/dt=(\w)/i,iSD:function(){with(this){if(w.location.hostname!="batest.pixnet.net")return 0;var demoType="";if(rDemoType.test(sTL))demoType=sTL.match(rDemoType)[1];return sFID=="2"&&demoType=="s"||sFID=="1"&&demoType=="w"||sFID=="2"&&isContent=="1"&&demoType=="c"?1:0}},gAMID:function(){with(this){if(iSD()){var m=location.href.match(/\?id=(\d+)/i);if(m&&m[1])return m[1]}if(rAMID.test(sTL)&&
rMSID.test(sTL)){var sMSID=sTL.match(rMSID)[1];if(sFID=="1"&&(sMSID==1||sMSID==2||sMSID==3||sMSID==4))return sTL.match(rAMID)[1];else if(sFID=="2")if(isContent=="1"&&(sMSID==5||sMSID==7||sMSID==8))return sTL.match(rAMID)[1];else if(isContent=="0"&&(sMSID==5||sMSID==6))return sTL.match(rAMID)[1]}return""}},iPV:function(){return this.gAMID()!=""},sADD:"js1.bloggerads.net",sSC:"/",iMB:"0",sH5:!!document.createElement("canvas").getContext?1:0,sFLASH:FD.i?1:0,sL:location.href,sMD:"d1ypub5wfz82gq.cloudfront.net/AdsService",
sCSS:"CSS/ba_ad.min.css",sADP:"getads.aspx",sPVP:"getads_pv.aspx",sF:"JS/ba.min.js",sFV:"v=180717001",sCD:"1",isWeb:"0",isContent:"0",hw:document.body==null?728:document.body.clientWidth,eXT:function(t){t.dEC(this,function(a){t[a]=this==window?null:this})},aPN:function(o,c){o.appendChild(c)},dEC:function(o,f){if(!o)return;if(!o.length||o.length==0)for(var _i in o){if(f.call(o[_i],_i)===false)break}else for(var _i=0;_i<o.length;_i++)if(f.call(o[_i],_i)===
false)break;return o},sATT:function(o,a,v){if(v){o[a]=v;return o}this.dEC(a,function(k){o[k]=this});return o},gBT:function(t,o){return(o||this.oD).getElementsByTagName(t)},gBI:function(i){return this.oD.getElementById(i)},gBC:function(c){return this.oD.getElementsByClassName(c)},gCE:function(t,a,i,iT){with(this){var _d=this.oD.createElement(t);this.sATT(_d,a);if(iT)this.aPN(_d,this.oD.createTextNode(i));else if(i)_d.innerHTML=i;return _d}},lJS:function(s,a){var _tn="script",_t="text/java"+_tn;with(this){t=
gBT("script")[0];t.parentNode.insertBefore(gCE(_tn,{type:_t,src:s,"async":"async"}),t)}},tB:function(t,a,i){return"<"+t+" "+(a||"")+">"+(i||"")+"</"+t+">"},gAD:function(){return this.gBI(this.sAD)},pAD:function(h){if(typeof h==="string"){var t=this.gCE("div",null,h);h=t.childNodes}var ad=this.gBI(this.sAD);while(h&&h.length&&h.length>0)this.aPN(ad,h[0])},lCSS:function(h){var _t="text/css",_r="stylesheet",_tn="link";with(this){t=gBT("script")[0];t.parentNode.insertBefore(gCE(_tn,{rel:_r,type:_t,href:h}),
t)}},eURI:function(d){return encodeURIComponent(d)},sI:function(cn){w[cn]=this;with(this){var ss=gBT("script");var u1,u2;if(isWeb==0){u1="//"+sADD+"/"+(isContent==1?"contentads.aspx":sFID=="2"?"ShowAds.aspx":"ShowBanner.aspx")+"?blogid="+sBID;u2="//ad2.bloggerads.net/"+(isContent==1?"contentads.aspx":sFID=="2"?"ShowAds.aspx":"ShowBanner.aspx")+"?blogid="+sBID}else{u1="//"+sADD+"/verify.aspx?w="+sBID+"&chartset=utf-8&f="+(sFID=="2"?"1":"5");u2="//"+sADD+"/verify.aspx?w="+sBID+"&f="+(sFID=="2"?"1":
"5")}for(var script=0,len=ss.length;script<len;script++){var s=ss[script];if(s.src.toLowerCase().indexOf(u1.toLowerCase())>=0||s.src.toLocaleLowerCase().indexOf(u2.toLowerCase())>=0){var n=oD.createElement("div");n.id=sAD;s.parentNode.insertBefore(n,s);var tcw=w.getComputedStyle(s.parentElement,null).getPropertyValue("width").replace("px","");hw=isNaN(tcw)?728:Math.ceil(tcw);break}}var cw=0,cItem;var h=w.location.hostname;var pixnet=/pixnet.net/i,blogspot=/blogspot./i,xuite=/xuite.net/i;if(h.match(pixnet))cItem=
gBI("article-content-inner");else if(h.match(blogspot))cItem=gBC("post-body")[0];else if(h.match(xuite))cItem=gBI("content_all");if(cItem!=undefined){var tcw=w.getComputedStyle(cItem,null).getPropertyValue("width").replace("px","");cw=isNaN(tcw)?728:Math.ceil(tcw)}lCSS([sSC,sMD,sCSS].join("/")+"?"+sFV);lJS([sSC,sMD,sF].join("/")+"?"+sFV);if(!iPV())lJS([sSC,sADD,sADP].join("/")+"?"+["blogid="+sBID,"fid="+sFID,"c="+cn,"d="+sCD,"sh5="+sH5,"sflash="+sFLASH,"isc="+isContent,"w="+(oD.body==null?0:oD.body.clientWidth),
"isw="+isWeb,"hw="+hw,"cw="+cw].join("&"));else lJS([sSC,sADD,sPVP].join("/")+"?"+["blogid="+sBID,"amid="+gAMID(),"isd="+iSD(),"c="+cn,"isc="+isContent].join("&"));lJS("//agent.aralego.com/sdk")}}};try{var c=new BA_CORE;c.sI("b59753499")}catch(e){}})(window);var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-1689570-36"]);_gaq.push(["_setDomainName","js1.bloggerads.net"]);_gaq.push(["_set","campaignParams","utm_campaign=&utm_source=BA&utm_medium=1"]);
_gaq.push(["_setAllowHash",false]);_gaq.push(["_trackPageview"]);(function(){var ga=document.createElement("script");ga.type="text/javascript";ga.async=true;ga.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(ga,s)})();